### ISSUE TITLE
Installation issues for non-bash shells

### ISSUE THREAD

**Issue by awvwgk** [rmera/goanalyze#2]
The current installation script is assuming a bash shell, is there any particular reason to restrict the installation to bash shells only? It doesn't seem that the project actually requires bash functionality in the first place.

I'm using a zsh under Linux which is not that uncommon.

**Comment by rmera** [comment]
Hi, I  actually just added a "TODO" on  that to the readme. 
The reason is very mundane. It's the shell I have always used, and the only one I have available for testing.
It should be just a matter of having INSTALL.py do the same thing it does in .bashrc, in .zprofile, but until I have the time to make a user with that shell and test that it works, I don't dare to add it.  I'll try to get to it during next week :-)

**Comment by rmera** [comment]
Ok, I decided to just add what I put in my previous comment to the installer. I simply marked it as "untested" in the README, but it is available.
